// <auto-generated />
using System;
using HamburgerShop.Models.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HamburgerShop.Migrations
{
    [DbContext(typeof(UygulamaDbContext))]
    [Migration("20230124204317_1")]
    partial class _1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("HamburgerShop.Models.Data.Classes.Boyut", b =>
                {
                    b.Property<int>("BoyutId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BoyutId"), 1L, 1);

                    b.Property<string>("BoyutAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("BoyutFiyati")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("BoyutId");

                    b.ToTable("Boyutlar");

                    b.HasData(
                        new
                        {
                            BoyutId = 1,
                            BoyutAdi = "100gr",
                            BoyutFiyati = 0m
                        },
                        new
                        {
                            BoyutId = 2,
                            BoyutAdi = "150gr",
                            BoyutFiyati = 24m
                        },
                        new
                        {
                            BoyutId = 3,
                            BoyutAdi = "200gr",
                            BoyutFiyati = 48m
                        });
                });

            modelBuilder.Entity("HamburgerShop.Models.Data.Classes.EkstraMalzeme", b =>
                {
                    b.Property<int>("EkstraMalzemeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EkstraMalzemeId"), 1L, 1);

                    b.Property<string>("EkstraMalzemeAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("EkstraMalzemeFiyati")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("SiparisId")
                        .HasColumnType("int");

                    b.HasKey("EkstraMalzemeId");

                    b.HasIndex("SiparisId");

                    b.ToTable("EkstraMalzemeler");

                    b.HasData(
                        new
                        {
                            EkstraMalzemeId = 1,
                            EkstraMalzemeAdi = "Hardal Sos",
                            EkstraMalzemeFiyati = 5m
                        },
                        new
                        {
                            EkstraMalzemeId = 2,
                            EkstraMalzemeAdi = "Acı Sos",
                            EkstraMalzemeFiyati = 6m
                        },
                        new
                        {
                            EkstraMalzemeId = 3,
                            EkstraMalzemeAdi = "Mayonez",
                            EkstraMalzemeFiyati = 4m
                        },
                        new
                        {
                            EkstraMalzemeId = 4,
                            EkstraMalzemeAdi = "Ketcap",
                            EkstraMalzemeFiyati = 4m
                        },
                        new
                        {
                            EkstraMalzemeId = 5,
                            EkstraMalzemeAdi = "Ranch Sos",
                            EkstraMalzemeFiyati = 7m
                        });
                });

            modelBuilder.Entity("HamburgerShop.Models.Data.Classes.Hamburger", b =>
                {
                    b.Property<int>("HamburgerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HamburgerId"), 1L, 1);

                    b.Property<string>("HamburgerAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("HamburgerFiyati")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("HamburgerFotograf")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("HamburgerId");

                    b.ToTable("Hamburgerler");

                    b.HasData(
                        new
                        {
                            HamburgerId = 1,
                            HamburgerAdi = "Cheese Burger",
                            HamburgerFiyati = 60m,
                            HamburgerFotograf = "cheeseburger.jpg"
                        },
                        new
                        {
                            HamburgerId = 2,
                            HamburgerAdi = "BigKing Burger",
                            HamburgerFiyati = 90m,
                            HamburgerFotograf = "big-king.jpg"
                        },
                        new
                        {
                            HamburgerId = 3,
                            HamburgerAdi = "KingBeef Burger",
                            HamburgerFiyati = 110m,
                            HamburgerFotograf = "kingbeefburger.jpg"
                        },
                        new
                        {
                            HamburgerId = 4,
                            HamburgerAdi = "Kofte Burger",
                            HamburgerFiyati = 85m,
                            HamburgerFotograf = "kofteburger.jpg"
                        },
                        new
                        {
                            HamburgerId = 5,
                            HamburgerAdi = "Tavuk Burger",
                            HamburgerFiyati = 50m,
                            HamburgerFotograf = "tavukburger.jpg"
                        });
                });

            modelBuilder.Entity("HamburgerShop.Models.Data.Classes.Icecek", b =>
                {
                    b.Property<int>("IcecekId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IcecekId"), 1L, 1);

                    b.Property<string>("IcecekAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("IcecekFiyati")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IcecekId");

                    b.ToTable("Icecekler");

                    b.HasData(
                        new
                        {
                            IcecekId = 1,
                            IcecekAdi = "Kola",
                            IcecekFiyati = 25m
                        },
                        new
                        {
                            IcecekId = 2,
                            IcecekAdi = "Fanta",
                            IcecekFiyati = 25m
                        },
                        new
                        {
                            IcecekId = 3,
                            IcecekAdi = "Ayran",
                            IcecekFiyati = 20m
                        },
                        new
                        {
                            IcecekId = 4,
                            IcecekAdi = "Su",
                            IcecekFiyati = 15m
                        },
                        new
                        {
                            IcecekId = 5,
                            IcecekAdi = "Soda",
                            IcecekFiyati = 18m
                        });
                });

            modelBuilder.Entity("HamburgerShop.Models.Data.Classes.Siparis", b =>
                {
                    b.Property<int>("SiparisId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SiparisId"), 1L, 1);

                    b.Property<int>("BoyutId")
                        .HasColumnType("int");

                    b.Property<int>("HamburgerId")
                        .HasColumnType("int");

                    b.Property<int?>("IcecekId")
                        .HasColumnType("int");

                    b.Property<byte>("SiparisAdet")
                        .HasColumnType("tinyint");

                    b.Property<decimal>("ToplamTutar")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("SiparisId");

                    b.HasIndex("BoyutId");

                    b.HasIndex("HamburgerId");

                    b.HasIndex("IcecekId");

                    b.ToTable("Siparisler");
                });

            modelBuilder.Entity("HamburgerShop.Models.Data.Classes.EkstraMalzeme", b =>
                {
                    b.HasOne("HamburgerShop.Models.Data.Classes.Siparis", "Siparis")
                        .WithMany("EkstraMalzemeler")
                        .HasForeignKey("SiparisId");

                    b.Navigation("Siparis");
                });

            modelBuilder.Entity("HamburgerShop.Models.Data.Classes.Siparis", b =>
                {
                    b.HasOne("HamburgerShop.Models.Data.Classes.Boyut", "Boyut")
                        .WithMany()
                        .HasForeignKey("BoyutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HamburgerShop.Models.Data.Classes.Hamburger", "Hamburger")
                        .WithMany()
                        .HasForeignKey("HamburgerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HamburgerShop.Models.Data.Classes.Icecek", "Icecek")
                        .WithMany()
                        .HasForeignKey("IcecekId");

                    b.Navigation("Boyut");

                    b.Navigation("Hamburger");

                    b.Navigation("Icecek");
                });

            modelBuilder.Entity("HamburgerShop.Models.Data.Classes.Siparis", b =>
                {
                    b.Navigation("EkstraMalzemeler");
                });
#pragma warning restore 612, 618
        }
    }
}
